# Generated by Django 3.0.5 on 2020-04-13 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='author',
        ),
    ]
