# Generated by Django 3.0.5 on 2020-04-15 08:23

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_management', '0002_auto_20200415_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salespost',
            name='contact',
            field=phone_field.models.PhoneField(blank=True, max_length=31),
        ),
    ]
